package ifneeded eAssist_importFiles 1.0 "[list source [file join $dir importFiles_gui.tcl]]
                                            [list source [file join $dir importFiles_code.tcl]]
                                            [list source [file join $dir importFiles_helpers_code.tcl]]
                                            [list source [file join $dir importFiles_helpers_gui.tcl]]
                                            [list source [file join $dir menusContext_gui.tcl]]
                                            [list source [file join $dir internalSamples_gui.tcl]]
                                            [list source [file join $dir internalSamples_code.tcl]]
                                            [list source [file join $dir splitAddresses_gui.tcl]]
                                            [list source [file join $dir splitAddresses_code.tcl]]
                                            [list source [file join $dir addDestination_codeAndGui.tcl]]
                                            [list source [file join $dir exportFiles_code.tcl]]
                                            [list source [file join $dir fileImporter_gui.tcl]]"